name: Run E2E Tests

on: [push]

jobs:
    run-e2e-tests:
        name: Run E2E Tests
        runs-on: ubuntu-latest

        services:
          db:
            image: postgres
            ports:
              - 5432:5432
            env:
              POSTGRES_PASSWORD: 123456
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '18'
                cache: 'npm'
            - run: npm ci
            - run: npm run test:e2e
              env:
                JWT_SECRET: testing
                DATABASE_URL: "postgresql://postgres:123456@localhost:5432/my_database?schema=public"