version: '3.1'

services:

  db:
    image: postgres
    restart: always
    # container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./data/pg:/data/postgres
  
  cache:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
